name: Manage Azure Infrastructure with Terraform

on:
  push:
    paths:
      - 'infra/scripts/**'
      - 'infra/terraform/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - 'infra/scripts/**'
      - 'infra/terraform/**'
      - '.github/workflows/terraform.yml'

env:
  ENV: 'production'
  STORAGE_ACCOUNT_TFSTATE_NAME: ${{ secrets.STORAGE_ACCOUNT_TFSTATE_NAME }}
  STORAGE_ACCOUNT_TFSTATE_CONTAINER_NAME: 'tfstate'
  STORAGE_ACCOUNT_HUMIDITYDATA_NAME: ${{ secrets.STORAGE_ACCOUNT_HUMIDITYDATA_NAME }}
  STORAGE_ACCOUNT_HUMIDITYDATA_CONTAINER_NAME: 'humiditydata'
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  RESOURCE_GROUP_NAME: 'data-project-humidity-home-rg'
  LOCATION: 'West Europe'
  PROJECT_NAME: 'data-project-humidity-adf' 

jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ env.ARM_CLIENT_ID }}","clientSecret":"${{ env.ARM_CLIENT_SECRET }}","subscriptionId":"${{ env.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ env.ARM_TENANT_ID }}"}'
      - name: Terraform Plan
        id: plan
        run: ./infra/scripts/tf_plan.sh
        env:
          ENV: ${{ env.ENV }}
          STORAGE_ACCOUNT_TFSTATE_NAME: ${{ env.STORAGE_ACCOUNT_TFSTATE_NAME }}
          STORAGE_ACCOUNT_TFSTATE_CONTAINER_NAME: ${{ env.STORAGE_ACCOUNT_TFSTATE_CONTAINER_NAME }}
          STORAGE_ACCOUNT_HUMIDITYDATA_NAME: ${{ env.STORAGE_ACCOUNT_HUMIDITYDATA_NAME }}
          STORAGE_ACCOUNT_HUMIDITYDATA_CONTAINER_NAME: ${{ env.STORAGE_ACCOUNT_HUMIDITYDATA_CONTAINER_NAME }}
          ARM_CLIENT_ID: ${{ env.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ env.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}
          RESOURCE_GROUP_NAME: ${{ env.RESOURCE_GROUP_NAME }}
          LOCATION: ${{ env.LOCATION }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ENV }}-tfplan
          path: infra/terraform/${{ env.ENV }}-tfplan
          if-no-files-found: error
      - name: Update Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })


  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform_plan
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ENV }}-tfplan
          path: infra/terraform/
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ env.ARM_CLIENT_ID }}","clientSecret":"${{ env.ARM_CLIENT_SECRET }}","subscriptionId":"${{ env.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ env.ARM_TENANT_ID }}"}'
      - name: Terraform Apply
        id: apply
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
        run: ./infra/scripts/tf_apply.sh
        env:
          ENV: ${{ env.ENV }}
          STORAGE_ACCOUNT_TFSTATE_NAME: ${{ env.STORAGE_ACCOUNT_TFSTATE_NAME }}
          ARM_CLIENT_ID: ${{ env.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ env.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}
      - name: Delete Artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          name: ${{ env.ENV }}-tfplan

